// <auto-generated />
using System;
using DocketSystemAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DocketSystemAPI.Migrations
{
    [DbContext(typeof(DocketDBContext))]
    partial class DocketDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DocketSystemAPI.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CapturerId");

                    b.Property<string>("CaseNo");

                    b.Property<string>("CaseType");

                    b.Property<string>("Description");

                    b.Property<string>("DetectiveID");

                    b.Property<string>("Media");

                    b.Property<int>("Status");

                    b.Property<int?>("UserId");

                    b.Property<string>("VictimFullName");

                    b.Property<string>("VictimID");

                    b.Property<DateTime>("date");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("DocketSystemAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName");

                    b.Property<string>("IDNumber");

                    b.Property<string>("Password");

                    b.Property<int>("UserType");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DocketSystemAPI.Models.victim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("CaptureIdNo");

                    b.Property<string>("CellNO");

                    b.Property<string>("FullName");

                    b.Property<string>("Gender");

                    b.Property<string>("IDNumber");

                    b.Property<string>("Password");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Victims");
                });

            modelBuilder.Entity("DocketSystemAPI.Models.Case", b =>
                {
                    b.HasOne("DocketSystemAPI.Models.User")
                        .WithMany("Cases")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DocketSystemAPI.Models.victim", b =>
                {
                    b.HasOne("DocketSystemAPI.Models.User")
                        .WithMany("Victims")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
